volumes:
  postgres-data:
  elastic-data:

services:
  web:
    build: .
    depends_on:
      - db
      - redis
      - elastic
    volumes:
      - .:/code
    ports:
      - "8005:8005"
  db:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - postgres-data:/var/lib/postgresql/data
  redis:
    image: redis:6
  worker:
    build: .
    command: python manage.py rqworker-pool default low --num-workers 2
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
      - elastic
  scheduler:
    build: .
    command: python manage.py run_scheduler
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
      - elastic
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.0
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    volumes:
      - elastic-data:/usr/share/elasticsearch/data
