volumes:
  postgres-data:
  elastic-data:

services:
  web:
    build: .
    depends_on:
      - db
      - redis
        #- elastic
    volumes:
      - .:/code
    ports:
      - "8005:8005"
  db:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - postgres-data:/var/lib/postgresql/data
  redis:
    image: redis:6
        #  elastic:
        #    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.0
        #    environment:
        #      - discovery.type=single-node
        #    volumes:
        #      - elastic-data:/usr/share/elasticsearch/data
