volumes:
  postgres-data:
  elastic-data:

version: '3'
services:
  web:
    build: .
    depends_on:
      - db
      - redis
    volumes:
      - .:/code
    ports:
      - "8005:8005"
  db:
    image: postgres:11
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - postgres-data:/var/lib/postgresql/data
  redis:
    image: redis:6
  celery:
    build: .
    command: celery -A funance worker --loglevel=info
    depends_on:
      - redis
    volumes:
      - .:/code
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:8
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
    volumes:
      - elastic-data:/usr/share/elasticsearch/data
