# Generated by Django 4.0.5 on 2022-07-02 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tickers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('currency', models.CharField(choices=[('US', 'USD')], default='US', max_length=2)),
                ('available_cash', models.DecimalField(decimal_places=4, max_digits=32)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funds', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FundPurchase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=32)),
                ('price', models.DecimalField(decimal_places=4, max_digits=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('purchased_at', models.DateTimeField()),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='funds.fund')),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fund_purchases', to='tickers.ticker')),
            ],
        ),
        migrations.CreateModel(
            name='FundAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('percentage', models.DecimalField(decimal_places=4, max_digits=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='funds.fund')),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fund_allocations', to='tickers.ticker')),
            ],
        ),
    ]
