# Generated by Django 4.0.5 on 2023-06-04 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundpurchase',
            name='quantity',
            field=models.DecimalField(decimal_places=8, max_digits=32),
        ),
    ]
