# Generated by Django 4.0.5 on 2023-06-04 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0002_alter_fundpurchase_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fund',
            name='available_cash',
        ),
        migrations.RemoveField(
            model_name='fund',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='fundallocation',
            name='percentage',
        ),
        migrations.AddField(
            model_name='fund',
            name='shares',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='fundallocation',
            name='shares',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='FundPurchase',
        ),
    ]
