# Generated by Django 5.1.7 on 2025-03-29 21:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("funds", "0004_remove_fundallocation_name_fund_created_at_and_more"),
        ("tickers", "0005_remove_ticker_current_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fund",
            name="shares",
        ),
        migrations.CreateModel(
            name="FundVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("active", models.BooleanField(default=False)),
                ("shares", models.PositiveIntegerField(default=1000)),
                (
                    "fund",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="funds.fund",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="funds.fundversion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FundVersionAllocation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("shares", models.PositiveIntegerField(default=0)),
                (
                    "ticker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fund_allocations",
                        to="tickers.ticker",
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocations",
                        to="funds.fundversion",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="FundAllocation",
        ),
        migrations.AddIndex(
            model_name="fundversion",
            index=models.Index(fields=["active"], name="funds_fundv_active_2bfbe7_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="fundversionallocation",
            unique_together={("version", "ticker")},
        ),
    ]
