# Generated by Django 5.1.7 on 2025-03-29 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("funds", "0005_remove_fund_shares_fundversion_fundversionallocation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fundversion",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="funds.fundversion",
            ),
        ),
    ]
