# Generated by Django 5.1.7 on 2025-03-30 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("funds", "0006_alter_fundversion_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="fund",
            name="active_version",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="funds.fundversion",
            ),
        ),
    ]
