# Generated by Django 5.1.7 on 2025-04-05 21:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("funds", "0009_fundversion_portfolio_shares_portfolio_shares"),
    ]

    operations = [
        migrations.CreateModel(
            name="PortfolioWeek",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField()),
                (
                    "sale_profit",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=32, null=True
                    ),
                ),
                (
                    "sale_interest",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=32, null=True
                    ),
                ),
                (
                    "generation_profit",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=32, null=True
                    ),
                ),
                (
                    "portfolio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weeks",
                        to="funds.portfolio",
                    ),
                ),
            ],
            options={
                "unique_together": {("portfolio", "date")},
            },
        ),
    ]
