# Generated by Django 5.1.7 on 2025-04-05 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("funds", "0010_portfolioweek"),
    ]

    operations = [
        migrations.AddField(
            model_name="portfolioweek",
            name="net_cost_basis",
            field=models.DecimalField(
                blank=True, decimal_places=8, max_digits=32, null=True
            ),
        ),
    ]
