# Generated by Django 5.1.7 on 2025-04-06 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("funds", "0012_fundversion_confidence_shift_percentage_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fundversionallocation",
            name="modifier",
            field=models.IntegerField(default=0),
        ),
    ]
