# Generated by Django 5.1.7 on 2025-04-10 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("funds", "0013_alter_fundversionallocation_modifier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fundversionallocation",
            name="modifier",
            field=models.IntegerField(default=100),
        ),
    ]
