# Generated by Django 5.1.7 on 2025-04-10 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("funds", "0014_alter_fundversionallocation_modifier"),
    ]

    operations = [
        migrations.AddField(
            model_name="fund",
            name="shares",
            field=models.PositiveIntegerField(default=1000),
        ),
    ]
