# Generated by Django 5.1.7 on 2025-04-10 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("funds", "0015_fund_shares"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fund",
            name="shares",
        ),
    ]
