# Generated by Django 5.1.7 on 2025-04-11 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("funds", "0016_remove_fund_shares"),
    ]

    operations = [
        migrations.AddField(
            model_name="portfolio",
            name="cash_monthly_confidence",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="portfolio",
            name="cash_quarterly_confidence",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="portfolio",
            name="cash_weekly_confidence",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
