# Generated by Django 5.1.7 on 2025-04-11 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("funds", "0017_portfolio_cash_monthly_confidence_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="portfolio",
            name="cash_monthly_confidence",
        ),
        migrations.RemoveField(
            model_name="portfolio",
            name="cash_quarterly_confidence",
        ),
        migrations.RemoveField(
            model_name="portfolio",
            name="cash_weekly_confidence",
        ),
        migrations.AddField(
            model_name="portfolio",
            name="cash_confidence_shift_percentage",
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AddField(
            model_name="portfolio",
            name="cash_modifier",
            field=models.IntegerField(default=100),
        ),
    ]
