# Generated by Django 5.1.7 on 2025-04-12 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("funds", "0018_remove_portfolio_cash_monthly_confidence_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="portfolio",
            old_name="cash_confidence_shift_percentage",
            new_name="confidence_shift_percentage",
        ),
        migrations.AddField(
            model_name="fundversion",
            name="portfolio_modifier",
            field=models.IntegerField(default=100),
        ),
    ]
