# Generated by Django 5.1.7 on 2025-05-19 11:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "funds",
            "0019_rename_cash_confidence_shift_percentage_portfolio_confidence_shift_percentage_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="fundversion",
            name="end_value",
            field=models.DecimalField(
                blank=True, decimal_places=8, max_digits=32, null=True
            ),
        ),
        migrations.AddField(
            model_name="fundversion",
            name="start_value",
            field=models.DecimalField(
                blank=True, decimal_places=8, max_digits=32, null=True
            ),
        ),
        migrations.AddField(
            model_name="fundversionallocation",
            name="end_value",
            field=models.DecimalField(
                blank=True, decimal_places=8, max_digits=32, null=True
            ),
        ),
        migrations.AddField(
            model_name="fundversionallocation",
            name="start_value",
            field=models.DecimalField(
                blank=True, decimal_places=8, max_digits=32, null=True
            ),
        ),
        migrations.CreateModel(
            name="PortfolioVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("active", models.BooleanField(default=False)),
                (
                    "start_value",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=32, null=True
                    ),
                ),
                (
                    "end_value",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=32, null=True
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="funds.portfolioversion",
                    ),
                ),
                (
                    "portfolio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="funds.portfolio",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="fundversion",
            name="portfolio_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fund_versions",
                to="funds.portfolioversion",
            ),
        ),
        migrations.AddField(
            model_name="portfolio",
            name="active_version",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="funds.portfolioversion",
            ),
        ),
    ]
