# Generated by Django 5.1.7 on 2025-07-27 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("funds", "0020_fundversion_end_value_fundversion_start_value_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="portfolioversion",
            options={"ordering": ("-created_at",)},
        ),
        migrations.AddField(
            model_name="portfolioversion",
            name="end_cash",
            field=models.DecimalField(
                blank=True, decimal_places=8, max_digits=32, null=True
            ),
        ),
        migrations.AddField(
            model_name="portfolioversion",
            name="ended_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="portfolioversion",
            name="start_cash",
            field=models.DecimalField(
                blank=True, decimal_places=8, max_digits=32, null=True
            ),
        ),
        migrations.AddField(
            model_name="portfolioversion",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
