# Generated by Django 5.1.7 on 2025-08-30 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("funds", "0021_alter_portfolioversion_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="portfolioweek",
            options={"ordering": ("-date",)},
        ),
    ]
