# Generated by Django 5.1.7 on 2025-08-30 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("funds", "0022_alter_portfolioweek_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portfolioversion",
            name="active",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name="portfolioversion",
            name="end_cash",
            field=models.DecimalField(
                blank=True, decimal_places=8, editable=False, max_digits=32, null=True
            ),
        ),
        migrations.AlterField(
            model_name="portfolioversion",
            name="end_value",
            field=models.DecimalField(
                blank=True, decimal_places=8, editable=False, max_digits=32, null=True
            ),
        ),
        migrations.AlterField(
            model_name="portfolioversion",
            name="ended_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="portfolioversion",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="funds.portfolioversion",
            ),
        ),
        migrations.AlterField(
            model_name="portfolioversion",
            name="portfolio",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="versions",
                to="funds.portfolio",
            ),
        ),
        migrations.AlterField(
            model_name="portfolioversion",
            name="start_cash",
            field=models.DecimalField(
                blank=True, decimal_places=8, editable=False, max_digits=32, null=True
            ),
        ),
        migrations.AlterField(
            model_name="portfolioversion",
            name="start_value",
            field=models.DecimalField(
                blank=True, decimal_places=8, editable=False, max_digits=32, null=True
            ),
        ),
        migrations.AlterField(
            model_name="portfolioversion",
            name="started_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
