# Generated by Django 5.1.7 on 2025-08-31 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("funds", "0023_alter_portfolioversion_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="portfolioversion",
            name="confidence_shift_percentage",
            field=models.PositiveIntegerField(blank=True, default=20, null=True),
        ),
        migrations.AddField(
            model_name="portfolioversion",
            name="shares",
            field=models.PositiveIntegerField(blank=True, default=10000, null=True),
        ),
    ]
