# Generated by Django 4.0.5 on 2022-07-01 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('symbol', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
