# Generated by Django 5.1.7 on 2025-03-21 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticker",
            name="current_price",
            field=models.DecimalField(
                blank=True, decimal_places=8, max_digits=16, null=True
            ),
        ),
    ]
