# Generated by Django 5.1.7 on 2025-03-22 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickers", "0002_ticker_current_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticker",
            name="current_price",
            field=models.DecimalField(
                blank=True, decimal_places=8, max_digits=32, null=True
            ),
        ),
    ]
