# Generated by Django 5.1.7 on 2025-03-23 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickers", "0003_alter_ticker_current_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticker",
            name="symbol",
            field=models.CharField(
                max_length=10, primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
