# Generated by Django 5.1.7 on 2025-04-05 13:36

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickers", "0005_remove_ticker_current_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticker",
            name="current_price",
            field=models.DecimalField(
                decimal_places=8, default=Decimal("0"), max_digits=32
            ),
        ),
    ]
