#!/usr/bin/env python3

################################################################################

from holdings.models import HoldingAccount

account = HoldingAccount.objects.get(pk='d65e5962-5567-4948-b4ea-24764c442bba')
account

from holdings.account import parse_and_sync_positions

try:
    parse_and_sync_positions(account)
except Exception:
    import pdb; pdb.post_mortem()
    raise


################################################################################

from holdings.models import HoldingAccount

account = HoldingAccount.objects.get(pk='d65e5962-5567-4948-b4ea-24764c442bba')
account

from holdings.account import parse_positions

positions = parse_positions(account)
positions

positions['GLDM'].quantity
