# Generated by Django 4.0.5 on 2023-06-04 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tickers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HoldingAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('currency', models.CharField(choices=[('US', 'USD')], default='US', max_length=2)),
                ('available_cash', models.DecimalField(decimal_places=4, max_digits=32)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holding_accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HoldingAccountPurchase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=32)),
                ('price', models.DecimalField(decimal_places=4, max_digits=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('purchased_at', models.DateTimeField()),
                ('holding_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='holdings.holdingaccount')),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holding_account_purchases', to='tickers.ticker')),
            ],
        ),
    ]
