# Generated by Django 4.0.5 on 2023-06-25 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holdings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holdingaccount',
            name='available_cash',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=32),
        ),
    ]
