# Generated by Django 4.2.4 on 2023-08-19 16:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("holdings", "0002_alter_holdingaccount_available_cash"),
    ]

    operations = [
        migrations.AddField(
            model_name="holdingaccount",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="holdingaccount",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
