# Generated by Django 4.2.4 on 2023-09-27 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("holdings", "0003_holdingaccount_created_at_holdingaccount_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="holdingaccountpurchase",
            name="price",
            field=models.DecimalField(decimal_places=8, max_digits=32),
        ),
    ]
