# Generated by Django 4.2.13 on 2024-12-07 17:15

from django.db import migrations, models
import django.db.models.deletion
import holdings.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("holdings", "0004_alter_holdingaccountpurchase_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="HoldingAccountDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document",
                    models.FileField(
                        max_length=256,
                        upload_to=holdings.models.holding_account_document_upload_to,
                    ),
                ),
                (
                    "holding_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="holdings.holdingaccount",
                    ),
                ),
            ],
        ),
    ]
