# Generated by Django 5.1.7 on 2025-03-08 17:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("holdings", "0005_holdingaccountdocument"),
    ]

    operations = [
        migrations.CreateModel(
            name="HoldingAccountAlias",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("discoverable", models.CharField(max_length=16)),
                ("alias", models.CharField(max_length=16)),
                (
                    "holding_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aliases",
                        to="holdings.holdingaccount",
                    ),
                ),
            ],
        ),
    ]
