# Generated by Django 5.1.7 on 2025-03-09 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("holdings", "0007_holdingaccount_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="holdingaccountdocument",
            name="order",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
