# Generated by Django 5.1.7 on 2025-03-09 13:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("holdings", "0008_holdingaccountdocument_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="HoldingAccountPosition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("ticker_symbol", models.CharField(max_length=16)),
                (
                    "holding_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="position",
                        to="holdings.holdingaccount",
                    ),
                ),
            ],
            options={
                "unique_together": {("holding_account", "ticker_symbol")},
            },
        ),
        migrations.CreateModel(
            name="HoldingAccountAction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("purchased_on", models.DateField()),
                (
                    "action",
                    models.CharField(
                        choices=[("buy", "Buy"), ("sell", "Sell")], max_length=16
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=8, max_digits=32)),
                ("price", models.DecimalField(decimal_places=8, max_digits=32)),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="holdings.holdingaccountposition",
                    ),
                ),
            ],
            options={
                "unique_together": {
                    ("position", "purchased_on", "action", "quantity", "price")
                },
            },
        ),
        migrations.DeleteModel(
            name="HoldingAccountPurchase",
        ),
    ]
