# Generated by Django 5.1.7 on 2025-03-09 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("holdings", "0009_holdingaccountposition_holdingaccountaction_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="holdingaccountposition",
            name="holding_account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="positions",
                to="holdings.holdingaccount",
            ),
        ),
    ]
