# Generated by Django 5.1.7 on 2025-03-09 20:21

import datetime
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("holdings", "0011_holdingaccountgeneration_holdingaccountsale"),
    ]

    operations = [
        migrations.AddField(
            model_name="holdingaccountsale",
            name="quantity",
            field=models.DecimalField(
                decimal_places=8, default=Decimal('0'), max_digits=32
            ),
            preserve_default=False,
        ),
    ]
