# Generated by Django 5.1.7 on 2025-03-09 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("holdings", "0012_holdingaccountsale_quantity"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="holdingaccountsale",
            unique_together={
                (
                    "position",
                    "quantity",
                    "purchase_date",
                    "purchase_price",
                    "sale_date",
                    "sale_price",
                )
            },
        ),
    ]
