# Generated by Django 5.1.7 on 2025-03-09 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("holdings", "0013_alter_holdingaccountsale_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="holdingaccountaction",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="holdingaccountgeneration",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="holdingaccountsale",
            unique_together=set(),
        ),
    ]
