# Generated by Django 5.1.7 on 2025-03-09 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("holdings", "0014_alter_holdingaccountaction_unique_together_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="holdingaccountaction",
            index=models.Index(
                fields=["purchased_on"], name="holdings_ho_purchas_8f343c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="holdingaccountgeneration",
            index=models.Index(fields=["date"], name="holdings_ho_date_864365_idx"),
        ),
        migrations.AddIndex(
            model_name="holdingaccountsale",
            index=models.Index(
                fields=["purchase_date"], name="holdings_ho_purchas_ca38e3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="holdingaccountsale",
            index=models.Index(
                fields=["sale_date"], name="holdings_ho_sale_da_39cc49_idx"
            ),
        ),
    ]
