# Generated by Django 5.1.7 on 2025-03-21 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "holdings",
            "0015_holdingaccountaction_holdings_ho_purchas_8f343c_idx_and_more",
        ),
        ("tickers", "0002_ticker_current_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="holdingaccountposition",
            name="ticker",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tickers.ticker",
            ),
        ),
    ]
