# Generated by Django 5.1.7 on 2025-03-22 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("holdings", "0016_holdingaccountposition_ticker"),
    ]

    operations = [
        migrations.AddField(
            model_name="holdingaccountaction",
            name="has_remaining_quantity",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="holdingaccountaction",
            name="remaining_quantity",
            field=models.DecimalField(
                blank=True, decimal_places=8, max_digits=32, null=True
            ),
        ),
        migrations.AddIndex(
            model_name="holdingaccountaction",
            index=models.Index(fields=["action"], name="holdings_ho_action_6eb5a2_idx"),
        ),
        migrations.AddIndex(
            model_name="holdingaccountaction",
            index=models.Index(
                fields=["has_remaining_quantity"], name="holdings_ho_has_rem_47fd25_idx"
            ),
        ),
    ]
