# Generated by Django 5.1.7 on 2025-03-23 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("holdings", "0018_alter_holdingaccountaction_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="holdingaccountposition",
            name="cost_basis",
            field=models.DecimalField(
                blank=True, decimal_places=8, max_digits=32, null=True
            ),
        ),
        migrations.AddField(
            model_name="holdingaccountposition",
            name="quantity",
            field=models.DecimalField(
                blank=True, decimal_places=8, max_digits=32, null=True
            ),
        ),
    ]
