# Generated by Django 5.1.7 on 2025-03-23 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("holdings", "0019_holdingaccountposition_cost_basis_and_more"),
        ("tickers", "0004_alter_ticker_symbol"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="holdingaccountposition",
            index=models.Index(
                fields=["quantity"], name="holdings_ho_quantit_b285f9_idx"
            ),
        ),
    ]
