# Generated by Django 5.1.7 on 2025-03-30 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("funds", "0008_portfolio_fund_portfolio"),
        ("holdings", "0021_alter_holdingaccountposition_ticker"),
    ]

    operations = [
        migrations.AddField(
            model_name="holdingaccount",
            name="portfolio",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="holding_accounts",
                to="funds.portfolio",
            ),
        ),
    ]
