# Generated by Django 5.1.7 on 2025-04-03 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("holdings", "0023_remove_holdingaccount_available_cash_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="holdingaccount",
            name="number",
            field=models.CharField(max_length=64),
        ),
    ]
